### ISSUE TITLE
Application versions?

### ISSUE THREAD

**Issue by bertalanimre** [indigophp/ansible-lemp#1]
What versions does this playbook install on the clients? Always the latest or specific ones? I'm asking cause I need PHP 5.6 and not other version.

**Comment by sagikazarmark** [comment]
Actually at the moment it does not install any PHP version, it is incomplete, not recommended for production usage.

**Comment by bertalanimre** [comment]
Though so just by looking at the files. Working on my own right now. I think it will be amaizing when it is done. :)
